from __future__ import annotations

import contextvars
import hashlib
import os
import subprocess
import textwrap
from pathlib import Path

from typing import Any

from PIL import Image, ImageDraw, ImageFont

_test_mode_override: contextvars.ContextVar[bool | None] = contextvars.ContextVar(
    "_test_mode_override", default=None
)


def is_test_mode() -> bool:
    override = _test_mode_override.get()
    if override is not None:
        return override
    return os.environ.get("PARALLAX_TEST_MODE", "").lower() in ("1", "true", "yes")


def is_mock_asset(path: "str | Path") -> bool:
    """Return True if the path looks like a shim-generated mock file.

    Mock files are named mock_*.png / mock_video_*.mp4 / mock_tts_*.wav —
    all sharing the `mock_` prefix on the filename stem. Live runs use this
    to detect and reject dry-run stubs that were locked into the plan.
    """
    return Path(path).name.startswith("mock_")


def output_dir() -> Path:
    return Path(os.environ.get("PARALLAX_OUTPUT_DIR", "output"))


def _load_font(size: int) -> Any:
    for candidate in (
        "/System/Library/Fonts/Helvetica.ttc",
        "/System/Library/Fonts/Supplemental/Arial.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ):
        if os.path.exists(candidate):
            try:
                return ImageFont.truetype(candidate, size)
            except OSError:
                continue
    return ImageFont.load_default()


def render_mock_image(
    prompt: str,
    model: str,
    out_dir: Path | None = None,
    resolution: str = "1080x1920",
) -> Path:
    """Render a PNG that contains the request parameters as readable text.

    This is the test-mode substitute for any real external image generator.
    The goal is full transparency: the returned file IS the record of what
    the agent asked for — no network, no spend.

    The image is drawn on a square canvas (so text always fits and stays
    legible), then center-cropped to the requested resolution's aspect.
    Output dimensions match the requested resolution within rounding.
    """
    out = out_dir or output_dir()
    try:
        out.mkdir(parents=True, exist_ok=True)
    except OSError as e:
        raise RuntimeError(f"shim: could not create output dir {out}: {e}") from e

    from .ffmpeg_utils import parse_resolution
    target_w, target_h = parse_resolution(resolution)

    # Draw on a square base sized to the longer of the two target dims, so
    # the prompt text stays at the same visual scale across resolutions.
    base = max(target_w, target_h)
    img = Image.new("RGB", (base, base), color=(30, 30, 46))
    draw = ImageDraw.Draw(img)
    label_font = _load_font(28)
    body_font = _load_font(36)

    wrapped = textwrap.fill(prompt, width=28)
    _, _, tw, th = draw.multiline_textbbox((0, 0), wrapped, font=body_font, spacing=10)
    label = f"SCENE · {model.upper()}"
    _, _, lw, lh = draw.textbbox((0, 0), label, font=label_font)

    total_h = lh + 24 + th
    y_start = (base - total_h) // 2

    draw.text(((base - lw) // 2, y_start), label, fill=(160, 160, 200), font=label_font)
    draw.multiline_text(
        ((base - tw) // 2, y_start + lh + 24),
        wrapped,
        fill=(240, 240, 255),
        font=body_font,
        spacing=10,
        align="center",
    )

    # Center-crop the square to the requested aspect ratio, then resize to
    # exactly the requested dimensions. Cropping (not stretching) preserves
    # the prompt text's legibility at any aspect.
    if target_w >= target_h:
        crop_h = int(round(base * target_h / target_w))
        top = (base - crop_h) // 2
        cropped = img.crop((0, top, base, top + crop_h))
    else:
        crop_w = int(round(base * target_w / target_h))
        left = (base - crop_w) // 2
        cropped = img.crop((left, 0, left + crop_w, base))
    final = cropped.resize((target_w, target_h), Image.LANCZOS)  # type: ignore[attr-defined]

    key = hashlib.sha1(f"{prompt}|{model}|{resolution}".encode()).hexdigest()[:10]
    path = out / f"mock_{key}.png"
    try:
        final.save(path)
    except OSError as e:
        raise RuntimeError(f"shim: could not write PNG {path}: {e}") from e
    return path


def render_mock_video(
    prompt: str,
    model: str,
    duration_s: float = 5.0,
    out_dir: Path | None = None,
    resolution: str = "1080x1920",
) -> Path:
    """Render a stub mp4 — solid-color background with the prompt drawn over it.

    Used in PARALLAX_TEST_MODE for image-to-video / text-to-video aliases.
    No network. The mp4 IS the record of what the agent asked for.
    """
    out = out_dir or output_dir()
    try:
        out.mkdir(parents=True, exist_ok=True)
    except OSError as e:
        raise RuntimeError(f"shim: could not create output dir {out}: {e}") from e

    key = hashlib.sha1(f"{prompt}|{model}|{duration_s}".encode()).hexdigest()[:10]
    path = out / f"mock_video_{model}_{key}.mp4"

    # Use a still PNG generated by render_mock_image, then loop it for `duration_s`.
    # Pass resolution through so the source still already matches the target
    # aspect — avoids any letterbox/pillarbox surprises in the scale+crop step.
    still = render_mock_image(
        prompt=f"[VIDEO {model.upper()}] {prompt}",
        model=model,
        out_dir=out,
        resolution=resolution,
    )
    from .ffmpeg_utils import parse_resolution
    w, h = parse_resolution(resolution)
    cmd = [
        "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
        "-loop", "1", "-i", str(still),
        "-t", f"{duration_s:.2f}",
        "-vf", f"scale={w}:{h}:force_original_aspect_ratio=increase,crop={w}:{h}",
        "-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p",
        "-r", "30",
        str(path),
    ]
    result = subprocess.run(cmd, capture_output=True)
    if result.returncode != 0:
        raise RuntimeError(
            f"shim: ffmpeg failed for mock video {path}: {result.stderr.decode(errors='replace')}"
        )
    return path


def render_mock_tts(
    text: str,
    voice: str,
    out_dir: Path | None = None,
    wpm: float = 165.0,
) -> tuple[Path, list[dict[str, Any]], float]:
    """Render a sine-wave WAV with wpm-derived duration. Returns (path, words, total_s).

    Per-word timestamps are evenly spaced across the duration so downstream
    align_scenes works without modification.
    """
    out = out_dir or output_dir()
    out.mkdir(parents=True, exist_ok=True)

    words_text = text.split()
    if not words_text:
        words_text = [""]
    seconds_per_word = 60.0 / max(wpm, 1.0)
    total = max(0.5, len(words_text) * seconds_per_word)

    words: list[dict[str, Any]] = []
    t = 0.0
    for w in words_text:
        words.append({"word": w, "start": round(t, 3), "end": round(t + seconds_per_word, 3)})
        t += seconds_per_word

    key = hashlib.sha1(f"{text}|{voice}".encode()).hexdigest()[:10]
    path = out / f"mock_tts_{voice}_{key}.wav"
    cmd = [
        "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
        "-f", "lavfi", "-i", f"sine=frequency=220:duration={total:.2f}",
        "-ac", "1", "-ar", "44100", str(path),
    ]
    result = subprocess.run(cmd, capture_output=True)
    if result.returncode != 0:
        raise RuntimeError(
            f"shim: ffmpeg failed for mock tts {path}: {result.stderr.decode(errors='replace')}"
        )
    return path, words, round(total, 3)
